### PR TITLE
Sagivmalihi/develop

### PR DESCRIPTION
**Pull request by fabriziomoscon**
- adding project gradle files
- private method for creating device

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
@sagivmalihi I tried to run `RNTwilioExample` with this code, but unfortunately it still crashes.

currentl issues:
- sometimes the device is not initialised properly after tapping the button
- crash after making a call

Furthermore I was checking the original Twilio project:
https://github.com/twilio/twilio-client-quickstart-android/blob/master/app/src/main/java/client/twilio/com/quickstart/ClientActivity.java#L162-L185
and it seems there is no else case for initialisation. Maybe this is the way forward for this project as well. What do you think?
Are you able to run the example at all? Does it crash for you?

Thanks for your help

**Comment by sagivmalihi** [comment]
I didn't get a chance to look on the example code yet. My guess (but it's just a guess) is that maybe you don't wait for the 'deviceReady' event in js code before attempting to call any other methods? 

It works quite well for my app, I added a simple dialer component.. basically look like this:

http://pastebin.com/NkgdpwSt

and doesn't crash ;)

**Comment by sagivmalihi** [comment]
Looking again it seems that you **are** waiting for deviceReady event. 
I wonder - what kind of crash are you getting? do you get a traceback (maybe hiding somewhere in the logs? did you try to 'adb logcat' and find something?)

**Comment by fabriziomoscon** [comment]
UPDATE
The logs included doesn't contain any useful information about the crash, all warning seems not critical things. The crash has been resolved. See comments below

Thanks for sharing your code. I am looking at it now... Nice use of `async/await` :)

I am also in contact with some guys at Twilio to help me fix my problems, but it is not a fast troubleshooting.
I will paste here few logs I can see in the debugger... maybe 4 eyes will find some important information there:

to reproduce:
- compile the RNTwilioExample in debug with android studio so I can see the log with Android monitor
- lunch `npm start` for the example
- activate remote JS debug on the app
- tap on init devide
- receive token (I can see in the JS log)
- trying to make a call
- receiving error: `device null`

```
D/com.rogchap.react.modules.twilio.TwilioModule: event sent connectionDidFail
W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
W/art: Attempt to remove local handle scope entry from IRT, ignoring
W/ResourceType: No package identifier when getting value for resource number 0x00000000
W/unknown:React: Tried to enqueue runnable on already finished thread: 'js... dropping Runnable.
W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {3b0d23f} sending message to a Handler on a dead thread
  java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {3b0d23f} sending message to a Handler on a dead thread
    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
    at android.os.Handler.enqueueMessage(Handler.java:631)
    at android.os.Handler.sendMessageAtTime(Handler.java:600)
    at android.os.Handler.sendMessageDelayed(Handler.java:570)
    at android.os.Handler.post(Handler.java:326)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:60)
    at com.facebook.react.bridge.ReactContext.runOnJSQueueThread(ReactContext.java:239)
    at com.facebook.react.uimanager.events.EventDispatcher$ScheduleDispatchFrameCallback.doFrame(EventDispatcher.java:258)
    at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    at android.view.Choreographer.doFrame(Choreographer.java:549)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
D/com.rogchap.react.modules.twilio.TwilioModule: event sent deviceReady
W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
W/art: Attempt to remove local handle scope entry from IRT, ignoring
W/ResourceType: No package identifier when getting value for resource number 0x00000000
D/com.rogchap.react.modules.twilio.TwilioModule: event sent deviceReady
E/com.rogchap.react.modules.twilio.TwilioModule: Device is null
D/com.rogchap.react.modules.twilio.TwilioModule: event sent connectionDidFail
```

**Comment by fabriziomoscon** [comment]
UPDATE
The logs included doesn't contain any useful information about the crash, all warning seems not critical things. The crash has been resolved. See comments below

the example app crashes just after making a call

to reproduce:

compile the RNTwilioExample in debug with android studio so I can see the log with Android monitor
lunch npm start for the example
activate remote JS debug on the app
tap on init device
receive token (I can see in the JS log), and all logs for initialisation Java module are ok
trying to make a call
app crashes: 

```
E/libc++abi: Pure virtual function called!
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 28431 (Thread-23922)
```

full crash log:

```
W/art: Suspending all threads took: 28.414ms
D/MediaManager: playing sound OUTGOING as id 1
D/SoundPoolPlayThread: play thread starting
D/SoundPoolPlayThread: starting playback
D/MediaManager: play complete for stream 1
I/PJSIP: 15:18:53.338   pjsua_call.c !Making call with acc #1 to sip:AP27b019639535456498a6b907cd4664fd@chunderm.gll.twilio.com;transport=TLS
I/PJSIP: 15:18:53.338    pjsua_aud.c  .Set sound device: capture=-1, playback=-2
I/PJSIP: 15:18:53.339    pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@16000/1/20ms
I/PJSIP: 15:18:53.339   opensl_dev.c  ...Creating OpenSL stream
W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client
W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client
D/PJSIP: 15:18:53.351   ec0xb8e939c8  ...Creating AEC
D/PJSIP: 15:18:53.351          speex  ...warning: Unknown speex_preprocess_ctl request: : 2
I/PJSIP: 15:18:53.351   ec0xb8e939c8  ...AEC created, clock_rate=16000, channel=1, samples per frame=320, tail length=200 ms, latency=0 ms
I/PJSIP: 15:18:53.351   opensl_dev.c  ...Starting OpenSL stream..
D/PJSIP: 15:18:53.440   opensl_dev.c !Recorder thread started
D/PJSIP: 15:18:53.663   opensl_dev.c !Player thread started
D/PJSIP: 15:18:53.663          speex  warning: discarded first playback frame
D/PJSIP: 15:18:53.663          speex  warning: discarded first playback frame
D/PJSIP: 15:18:53.663          speex  warning: discarded first playback frame
I/PJSIP: 15:18:53.664   opensl_dev.c !...OpenSL stream started
D/PJSIP: 15:18:53.664  dlg0xb8ec0084  .UAC dialog created
D/PJSIP: 15:18:53.664  dlg0xb8ec0084  ..Session count inc to 2 by mod-pjsua
I/PJSIP: 15:18:53.664  pjsua_media.c  .Call 0: initializing media..
D/PJSIP: 15:18:53.669          speex !warning: discarded first playback frame
D/PJSIP: 15:18:53.669          speex  warning: discarded first playback frame
I/PJSIP: 15:18:53.671  pjsua_media.c !..RTP socket reachable at 192.168.1.102:4444
I/PJSIP: 15:18:53.671  pjsua_media.c  ..RTCP socket reachable at 192.168.1.102:4445
I/PJSIP: 15:18:53.671  pjsua_media.c  ..Media index 0 selected for audio call 0
D/PJSIP: 15:18:53.671  dlg0xb8ec0084  ..Session count dec to 2 by mod-pjsua
D/Call(native): tw_call_get already exists
D/CallControlManager: onCallSDPCreated notification received
D/PJSIP: 15:18:53.672  dlg0xb8ec0084  .Module mod-invite added as dialog usage, data=0xb8ce732c
D/PJSIP: 15:18:53.672  dlg0xb8ec0084  ..Session count inc to 4 by mod-invite
D/PJSIP: 15:18:53.672  dlg0xb8ec0084  .Module mod-100rel added as dialog usage, data=0xb8ec4bb0
D/PJSIP: 15:18:53.672  dlg0xb8ec0084  .100rel module attached
D/PJSIP: 15:18:53.672  inv0xb8ec0084  .UAC invite session created for dialog dlg0xb8ec0084
D/PJSIP: 15:18:53.672       endpoint  .Request msg INVITE/cseq=7164 (tdta0xb8ec4bf0) created.
D/PJSIP: 15:18:53.672  inv0xb8ec0084  ..Sending Request msg INVITE/cseq=7164 (tdta0xb8ec4bf0)
D/PJSIP: 15:18:53.672  dlg0xb8ec0084  ...Sending Request msg INVITE/cseq=7164 (tdta0xb8ec4bf0)
D/PJSIP: 15:18:53.672  tsx0xb8ec6c04  ....Transaction created for Request msg INVITE/cseq=7163 (tdta0xb8ec4bf0)
D/PJSIP: 15:18:53.673  tsx0xb8ec6c04  ...Sending Request msg INVITE/cseq=7163 (tdta0xb8ec4bf0) in state Null
D/PJSIP: 15:18:53.673  sip_resolve.c  ....Starting async DNS SRV query: target=_sips._tcp.chunderm.gll.twilio.com, transport=TLS, port=0
D/PJSIP: 15:18:53.673 _sips._tcp.chu  ....Starting async DNS SRV query_job: target=_sips._tcp.chunderm.gll.twilio.com:5061
I/PJSIP: 15:18:53.674     resolver.c  ....Transmitting 52 bytes to NS 0 (192.168.1.254:53): DNS SRV query for _sips._tcp.chunderm.gll.twilio.com: Success
D/PJSIP: 15:18:53.674  tsx0xb8ec6c04  ....State changed from Null to Calling, event=TX_MSG
D/PJSIP: 15:18:53.674  dlg0xb8ec0084  .....Transaction tsx0xb8ec6c04 state changed to Calling
D/UserAgent(native): got on_call_state for call id 0
D/Call(native): tw_call_get already exists
D/UserAgent(native): ... forwarding to java
D/com.rogchap.react.modules.twilio.TwilioModule: onConnecting
D/com.rogchap.react.modules.twilio.TwilioModule: event sent connectionDidStartConnecting
D/Call(native): tw_call_get already exists
D/UserAgent(native): on_call_tsx_state status code 0
D/UserAgent(native): SIP message type INVITE
D/PJSIP: 15:18:53.954     resolver.c !Received 140 bytes DNS response from 192.168.1.254:53
D/PJSIP: 15:18:53.954     resolver.c  Nameserver 192.168.1.254:53 state changed Active --> Active
D/PJSIP: 15:18:53.954 _sips._tcp.chu  SRV query_job for _sips._tcp.chunderm.gll.twilio.com completed, 2 of 2 total entries selected:
D/PJSIP: 15:18:53.954 _sips._tcp.chu   0: SRV 10 100 10194 chunderm1.ie1.twilio.com (-)
D/PJSIP: 15:18:53.954 _sips._tcp.chu   1: SRV 10 100 10194 chunderm0.ie1.twilio.com (-)
D/PJSIP: 15:18:53.954 _sips._tcp.chu  Starting async DNS A query_job for chunderm1.ie1.twilio.com
D/PJSIP: 15:18:53.954     resolver.c  Picked up DNS A record for chunderm1.ie1.twilio.com from cache, ttl=234
D/PJSIP: 15:18:53.954 _sips._tcp.chu  DNS A for chunderm1.ie1.twilio.com: 54.77.198.98
D/PJSIP: 15:18:53.954 _sips._tcp.chu  Starting async DNS A query_job for chunderm0.ie1.twilio.com
D/PJSIP: 15:18:53.954     resolver.c  Picked up DNS A record for chunderm0.ie1.twilio.com from cache, ttl=234
D/PJSIP: 15:18:53.954 _sips._tcp.chu  DNS A for chunderm0.ie1.twilio.com: 54.77.198.97
D/PJSIP: 15:18:53.955 _sips._tcp.chu  Server resolution complete, 2 server entry(s) found
I/PJSIP: 15:18:53.955 tlsc0xb8ec8d7c  TLS client transport created
I/PJSIP: 15:18:53.955 tlsc0xb8ec8d7c  TLS transport 192.168.1.102:46210 is connecting to chunderm.gll.twilio.com:10194...
I/PJSIP: 15:18:53.956   pjsua_core.c  TX 1750 bytes Request msg INVITE/cseq=7163 (tdta0xb8ec4bf0) to TLS 54.77.198.98:10194:
                                                            X-Twilio-Client: %7B%22p%22%3A%22android%22%2C%22v%22%3A%22UNKNOWN%22%2C%22mobile%22%3A%7B%22name%22%3A%22occam%22%2C%22produc

                                                            --end msg--
D/UserAgent(native): got on_transport_state
D/TW-Transports(native): transport insertion status: 1
D/UserAgent(native): NB: onTransportState()'s stateInfo var is not wrapped and will always be null
D/UserAgent(native): ... forwarding to java
I/PJSIP: 15:18:54.090 tlsc0xb8ec8d7c  TLS transport 192.168.1.102:46210 is connected to chunderm.gll.twilio.com:10194
D/PJSIP: 15:18:54.135 sip_endpoint.c  Processing incoming message: Response msg 302/INVITE/cseq=7163 (rdata0xb8ec8f48)
I/PJSIP: 15:18:54.135   pjsua_core.c  .RX 509 bytes Response msg 302/INVITE/cseq=7163 (rdata0xb8ec8f48) from TLS 54.77.198.98:10194:

                                                            --end msg--
D/PJSIP: 15:18:54.135  tsx0xb8ec6c04  .Incoming Response msg 302/INVITE/cseq=7163 (rdata0xb8ec8f48) in state Calling
D/PJSIP: 15:18:54.135       endpoint  ..Request msg ACK/cseq=7163 (tdta0xb8ed02a8) created.
I/PJSIP: 15:18:54.135   pjsua_core.c  ..TX 476 bytes Request msg ACK/cseq=7163 (tdta0xb8ed02a8) to TLS 54.77.198.98:10194:

                                                            --end msg--
D/PJSIP: 15:18:54.136  tsx0xb8ec6c04  ..State changed from Calling to Completed, event=RX_MSG
D/PJSIP: 15:18:54.136  dlg0xb8ec0084  ...Received Response msg 302/INVITE/cseq=7163 (rdata0xb8ec8f48)
D/PJSIP: 15:18:54.136  dlg0xb8ec0084  ...Transaction tsx0xb8ec6c04 state changed to Completed
D/UserAgent(native): In on_call_redirected, call_id
D/PJSIP: 15:18:54.136  dlg0xb8ec0084  .....Session count inc to 3 by mod-invite
D/PJSIP: 15:18:54.136  dlg0xb8ec0084  .....Session count dec to 3 by mod-invite
D/PJSIP: 15:18:54.136  inv0xb8ec0084  .....Sending Request msg INVITE/cseq=7163 (tdta0xb8ec4bf0)
D/PJSIP: 15:18:54.136  dlg0xb8ec0084  ......Sending Request msg INVITE/cseq=7163 (tdta0xb8ec4bf0)
D/PJSIP: 15:18:54.136  tsx0xb8edfd5c  .......Transaction created for Request msg INVITE/cseq=7164 (tdta0xb8ec4bf0)
D/PJSIP: 15:18:54.136  tsx0xb8edfd5c  ......Sending Request msg INVITE/cseq=7164 (tdta0xb8ec4bf0) in state Null
D/PJSIP: 15:18:54.136  sip_resolve.c  .......Target '54.171.100.172:10194' type=TLS resolved to '54.171.100.172:10194' type=TLS (TLS transport)
I/PJSIP: 15:18:54.137 tlsc0xb8ed3c24  .......TLS client transport created
I/PJSIP: 15:18:54.137 tlsc0xb8ed3c24  .......TLS transport 192.168.1.102:53377 is connecting to 54.171.100.172:10194...
I/PJSIP: 15:18:54.138   pjsua_core.c  .......TX 1712 bytes Request msg INVITE/cseq=7164 (tdta0xb8ec4bf0) to TLS 54.171.100.172:10194:
                                                            X-Twilio-Client: %7B%22p%22%3A%22android%22%2C%22v%22%3A%22UNKNOWN%22%2C%22mobile%22%3A%7B%22name%22%3A%22occam%22%2C%22product%22%3A%22LGE%20Nexus%204%22%

                                                            --end msg--
D/PJSIP: 15:18:54.138  tsx0xb8edfd5c  .......State changed from Null to Calling, event=TX_MSG
D/PJSIP: 15:18:54.138  dlg0xb8ec0084  ........Transaction tsx0xb8edfd5c state changed to Calling
D/Call(native): tw_call_get already exists
D/UserAgent(native): on_call_tsx_state status code 0
D/UserAgent(native): SIP message type INVITE
D/Call(native): tw_call_get already exists
D/UserAgent(native): on_call_tsx_state status code 302
D/UserAgent(native): SIP message type INVITE
D/PJSIP: 15:18:54.142  tsx0xb8ec6c04  Timeout timer event
D/PJSIP: 15:18:54.142  tsx0xb8ec6c04  .State changed from Completed to Terminated, event=TIMER
D/PJSIP: 15:18:54.142  dlg0xb8ec0084  ..Transaction tsx0xb8ec6c04 state changed to Terminated
D/Call(native): tw_call_get already exists
D/UserAgent(native): on_call_tsx_state status code 302
D/UserAgent(native): SIP message type INVITE
D/PJSIP: 15:18:54.146  tsx0xb8ec6c04  Timeout timer event
D/PJSIP: 15:18:54.146  tsx0xb8ec6c04  .State changed from Terminated to Destroyed, event=TIMER
D/PJSIP: 15:18:54.146 tdta0xb8ed02a8  ..Destroying txdata Request msg ACK/cseq=7163 (tdta0xb8ed02a8)
D/PJSIP: 15:18:54.146  tsx0xb8ec6c04  Transaction destroyed!
D/UserAgent(native): got on_transport_state
D/TW-Transports(native): transport insertion status: 1
D/UserAgent(native): NB: onTransportState()'s stateInfo var is not wrapped and will always be null
D/UserAgent(native): ... forwarding to java
I/PJSIP: 15:18:54.461 tlsc0xb8ed3c24  TLS transport 192.168.1.102:53377 is connected to 54.171.100.172:10194
D/PJSIP: 15:18:54.830 sip_endpoint.c  Processing incoming message: Response msg 100/INVITE/cseq=7164 (rdata0xb8ed3df0)
I/PJSIP: 15:18:54.831   pjsua_core.c  .RX 398 bytes Response msg 100/INVITE/cseq=7164 (rdata0xb8ed3df0) from TLS 54.171.100.172:10194:

                                                            --end msg--
D/PJSIP: 15:18:54.831  tsx0xb8edfd5c  .Incoming Response msg 100/INVITE/cseq=7164 (rdata0xb8ed3df0) in state Calling
D/PJSIP: 15:18:54.831  tsx0xb8edfd5c  ..State changed from Calling to Proceeding, event=RX_MSG
D/PJSIP: 15:18:54.831  dlg0xb8ec0084  ...Received Response msg 100/INVITE/cseq=7164 (rdata0xb8ed3df0)
D/PJSIP: 15:18:54.831  dlg0xb8ec0084  ...Transaction tsx0xb8edfd5c state changed to Proceeding
D/Call(native): tw_call_get already exists
D/UserAgent(native): on_call_tsx_state status code 100
D/UserAgent(native): SIP message type INVITE
D/PJSIP: 15:18:54.900 sip_endpoint.c  Processing incoming message: Response msg 180/INVITE/cseq=7164 (rdata0xb8ed3df0)
I/PJSIP: 15:18:54.900   pjsua_core.c  .RX 599 bytes Response msg 180/INVITE/cseq=7164 (rdata0xb8ed3df0) from TLS 54.171.100.172:10194:

                                                            --end msg--
D/PJSIP: 15:18:54.900  tsx0xb8edfd5c  .Incoming Response msg 180/INVITE/cseq=7164 (rdata0xb8ed3df0) in state Proceeding
D/PJSIP: 15:18:54.900  tsx0xb8edfd5c  ..State changed from Proceeding to Proceeding, event=RX_MSG
D/PJSIP: 15:18:54.900  dlg0xb8ec0084  ...Received Response msg 180/INVITE/cseq=7164 (rdata0xb8ed3df0)
D/PJSIP: 15:18:54.900  dlg0xb8ec0084  ....Route-set updated
D/PJSIP: 15:18:54.900  dlg0xb8ec0084  ...Transaction tsx0xb8edfd5c state changed to Proceeding
D/UserAgent(native): got on_call_state for call id 0
D/Call(native): tw_call_get already exists
D/UserAgent(native): ... forwarding to java
D/Call(native): tw_call_get already exists
D/UserAgent(native): on_call_tsx_state status code 180
D/UserAgent(native): SIP message type INVITE
D/PJSIP: 15:18:54.993 sip_endpoint.c  Processing incoming message: Response msg 200/INVITE/cseq=7164 (rdata0xb8ed3df0)
I/PJSIP: 15:18:54.993   pjsua_core.c  .RX 916 bytes Response msg 200/INVITE/cseq=7164 (rdata0xb8ed3df0) from TLS 54.171.100.172:10194:
                                                            a=pti

                                                            --end msg--
D/PJSIP: 15:18:54.993  tsx0xb8edfd5c  .Incoming Response msg 200/INVITE/cseq=7164 (rdata0xb8ed3df0) in state Proceeding
D/PJSIP: 15:18:54.993  tsx0xb8edfd5c  ..State changed from Proceeding to Terminated, event=RX_MSG
D/PJSIP: 15:18:54.993  dlg0xb8ec0084  ...Received Response msg 200/INVITE/cseq=7164 (rdata0xb8ed3df0)
D/PJSIP: 15:18:54.993  dlg0xb8ec0084  ....Route-set updated
D/PJSIP: 15:18:54.993  dlg0xb8ec0084  ....Route-set frozen
D/PJSIP: 15:18:54.993  dlg0xb8ec0084  ...Transaction tsx0xb8edfd5c state changed to Terminated
D/UserAgent(native): got on_call_state for call id 0
D/Call(native): tw_call_get already exists
D/UserAgent(native): ... forwarding to java
D/PJSIP: 15:18:54.995  inv0xb8ec0084  ....Got SDP answer in Response msg 200/INVITE/cseq=7164 (rdata0xb8ed3df0)
D/PJSIP: 15:18:54.995  inv0xb8ec0084  ....SDP negotiation done, status=0
D/PJSIP: 15:18:54.995   pjsua_call.c  .....Call 0: remote NAT type is 0 (Unknown)
I/PJSIP: 15:18:54.995  pjsua_media.c  .....Call 0: updating media..
I/PJSIP: 15:18:54.995    pjsua_aud.c  ......Audio channel update..
D/PJSIP: 15:18:54.995          rtp.c  .......pjmedia_rtp_session_init: ses=0xb8ee7590, default_pt=0, ssrc=0x312928d2
D/PJSIP: 15:18:54.996          rtp.c  .......pjmedia_rtp_session_init: ses=0xb8ee7c18, default_pt=0, ssrc=0x312928d2
D/PJSIP: 15:18:54.996       stream.c  .......Stream strm0xb8ee56e4 created
I/PJSIP: 15:18:54.996 strm0xb8ee56e4  .......Encoder stream started
I/PJSIP: 15:18:54.996 strm0xb8ee56e4  .......Decoder stream started
D/PJSIP: 15:18:54.996     resample.c  .......resample created: high qualiy, large filter, in/out rate=8000/16000
D/PJSIP: 15:18:54.996     resample.c  .......resample created: high qualiy, large filter, in/out rate=16000/8000
I/PJSIP: 15:18:54.996  pjsua_media.c  ......Audio updated, stream #0: PCMU (sendrecv)
D/UserAgent(native): got on_call_media_state for call id 0
D/Call(native): tw_call_get already exists
D/UserAgent(native): ... forwarding to java
I/PJSIP: 15:18:55.007    pjsua_aud.c  .....Conf connect: 0 --> 1
I/PJSIP: 15:18:55.007   conference.c  ......Port 0 (OpenSL ES Audio) transmitting to port 1 (sip:AP27b019639535456498a6b907cd4664fd@chunderm.gll.twilio.com;transport=TLS)
I/PJSIP: 15:18:55.007    pjsua_aud.c  .....Conf connect: 1 --> 0
I/PJSIP: 15:18:55.007   conference.c  ......Port 1 (sip:AP27b019639535456498a6b907cd4664fd@chunderm.gll.twilio.com;transport=TLS) transmitting to port 0 (OpenSL ES Audio)
D/PJSIP: 15:18:55.008  inv0xb8ec0084  ....Received Response msg 200/INVITE/cseq=7164 (rdata0xb8ed3df0), sending ACK
I/PJSIP: 15:18:55.008   Master/sound !Underflow, buf_cnt=0, will generate 1 frame
D/PJSIP: 15:18:55.008 strm0xb8ee56e4  Jitter buffer is bufferring (prefetch=0), plc invoked
D/PJSIP: 15:18:55.010 strm0xb8ee56e4  Start talksprut..
D/PJSIP: 15:18:55.013       endpoint !....Request msg ACK/cseq=7164 (tdta0xb8ef60f8) created.
D/PJSIP: 15:18:55.014  dlg0xb8ec0084  .....Sending Request msg ACK/cseq=7164 (tdta0xb8ef60f8)
D/PJSIP: 15:18:55.014  sip_resolve.c  .....Starting async DNS A query: target=ec2-54-171-100-172.eu-west-1.compute.amazonaws.com, transport=TLS, port=10194
I/PJSIP: 15:18:55.014     resolver.c  .....Transmitting 68 bytes to NS 0 (192.168.1.254:53): DNS A query for ec2-54-171-100-172.eu-west-1.compute.amazonaws.com: Success
D/UserAgent(native): got on_call_state for call id 0
D/Call(native): tw_call_get already exists
D/UserAgent(native): ... forwarding to java
E/libc++abi: Pure virtual function called!
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 28431 (Thread-23922)
W/AudioTrack: releaseBuffer() track 0xb8cf4400 disabled due to previous underrun, restarting
D/PJSIP: 17:31:33.744          speex !warning: No playback frame available (your application is buggy and/or got xruns)
D/PJSIP: 17:31:33.745          speex  warning: No playback frame available (your application is buggy and/or got xruns)
```

**Comment by fabriziomoscon** [comment]
UPDATE I fixed the above crash!
https://github.com/fabriziomoscon/react-native-twilio/commit/e310969d46c8f5eb897a47f553a61654dc6e162a

The above logs doesn't contain any useful information to solve this, all warning seems not critical things.

It seems that 2 methods called by the EventListener inside Twilio code don't like sending events with react `RCTDeviceEventEmitter`:
- onConnected
- onDisconnected

Commenting out the event sender fixes the crash.

There are other crashes now for other reasons though...

**Comment by sagivmalihi** [comment]
cool! let me know when you manage to clear it all up !

**Pull request merged**
